# Generated by Django 5.2.9 on 2025-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_offensive', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('safe', 'Safe'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='safe', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('categories', models.JSONField(default=list)),
                ('flagged_terms', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
