# Generated by Django 6.0.2 on 2026-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='flagged_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
