# Generated by Django 6.0 on 2026-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_analysisresult_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='emoji_detections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='mode',
            field=models.CharField(choices=[('kid', 'Kid'), ('adult', 'Adult')], default='adult', max_length=10),
        ),
    ]
